steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/GoogleCloudPlatform/microservices-demo.git']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/shippingservice', './microservices-demo/src/shippingservice/']
images: ['gcr.io/$PROJECT_ID/shippingservice']