apiVersion: v1
kind: Service
metadata:
  name: {{ include "emailservice.fullname" . }}
  labels:
{{ include "emailservice.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "emailservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
