apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-external
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
