apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}-service
  labels:
{{ include "frontend.labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
