apiVersion: v1
kind: Service
metadata:
  name: {{ include "paymentservice.fullname" . }}
  labels:
{{ include "paymentservice.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "paymentservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
